In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

In [9]:
k = 3

In [24]:
X = np.array([1,1.2,1.4,1.6,1.8,2.0,2.8,2.9,2.10,2.5,2.9,6])
Y = np.array([0,0,0,0,1,0,1,0,1,1,1,1])

In [16]:
# def mutual_information_knn(X, Y, k):
"""
Estimate mutual information between a continuous random variable X and a discrete random variable Y using k-NN method.

Parameters:
    X (ndarray): A 1D numpy array of size N containing the values of the continuous random variable X.
    Y (ndarray): A 1D numpy array of size N containing the values of the discrete random variable Y.
    k (int): The number of nearest neighbors to use for discretization.

Returns:
    mi (float): The estimated mutual information between X and Y.
"""
n = len(X)
nbrs = NearestNeighbors(n_neighbors=k, algorithm='ball_tree').fit(X.reshape(-1,1))
distances, indices = nbrs.kneighbors(X.reshape(-1,1))

In [62]:
P_X = np.zeros(k)
P_Y = np.zeros(np.max(Y)+1)
P_XY = np.zeros((k, np.max(Y)+1))

i = 0
# para cada ponto
while i < 3:
    P_X[0] += 1
    
    # somar 1 quando encontrar algum ponto de alguma classe
    P_Y[Y[i]] += 1
    
    # somar 1 na distribuicao de probabilidade conjunta, para encontrar 1 
    P_XY[0, Y[i]] += 1
    
    # para cada k
    # 1 porque nao pegamos a distancia com ele e ele mesmo porque eh zero
    for j in range(1,k):
        # distancia do ponto i para o j nearest neighbor
        d = distances[i,j]
        
        w = np.exp(-d**2 / (2*np.var(X)))
        
        P_X[j] += w
        P_XY[j, Y[i]] += w
        print(P_X)
        
    i = i + 1

P_X /= n*k
P_Y /= n
P_XY /= n

mi = 0
for i in range(k):
    for j in range(np.max(Y)+1):
        if P_XY[i,j] > 0:
            mi += P_XY[i,j] * np.log(P_XY[i,j] / (P_X[i] * P_Y[j]))

[1.         0.98760987 0.        ]
[1.         0.98760987 0.95135297]
[2.         1.97521973 0.95135297]
[2.         1.97521973 1.93896283]
[3.         2.9628296  1.93896283]
[3.        2.9628296 2.9265727]


In [60]:
P_X

array([0.02777778, 0.02743361, 0.02642647])

In [51]:
P_XY

array([[0.08333333, 0.        ],
       [0.08230082, 0.        ],
       [0.07927941, 0.        ]])

In [52]:
P_Y

array([0.08333333, 0.        ])

In [5]:


mi = mutual_information_knn(X, y, k = 4)
print(mi)

NameError: name 'mutual_information_knn' is not defined